### ISSUE TITLE
Shopping Items List

### ISSUE THREAD

**Issue by rvoll** [rvoll/capstone-shopping-buddy#6]
# Shopping Items List

## Value Proposition

**As a user**

**I want to** browse a well-organised list of shopping items,

**so that** I can easily see what I need to buy.

## Description

Capstone Student Todo: Add wireframes

## Acceptance Criteria

- The homepage displays a list of shopping items.
- The shopping list is headlined with its purpose.
- Each item listing includes:
  - Shopping item name
  - Shopping item quantity
  - Shopping item category
- A counter displays the total number of items currently on the shopping list.
- Each category is visually differentiated, for example, by using different colours.
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [ ] Create feature branch `feature/shopping-items-list`
- [ ] Inspect and adapt the example data in the [assets folder](./assets/shopping-items.json)
  - [ ] Add an `imageUrl` for each shopping item, for example from [unsplash.com](unsplash.com). You first need the image in the User Story [Shopping Item Details](./shopping-item-details.md)
- [ ] Capstone Student Todo: Add tasks

----

### 📒 Handout/Link List
- [React with Arrays](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/react-with-arrays/react-with-arrays.md)
  - Knowing how to use `.map()` to render lists in JSX
  - Understanding how to render items from an array of objects
  - Knowing to add a unique key for list items
